version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4
  python: circleci/python@2.1.1
  #shellcheck: circleci/shellcheck@1.0.0

workflows:
  test:
    jobs:
      - test-py31011
      #- shellcheck/check

jobs:
  test-py31011: &test-template
    working_directory: ~/mushroom
    docker:
      - image: cimg/python:3.10.11 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          PIPENV_VENV_IN_PROJECT: false
          CODECOV_TOKEN: 01359775-2d3e-4223-a0ef-ecc88779e801
    steps:
      - checkout
      # - run: sudo chown -R circleci:circleci /usr/local/bin
      # - run: sudo chown -R circleci:circleci /usr/local/lib/python3.10/site-packages
      # - restore_cache:  # ensure this step occurs *before* installing dependencies
      #     key: deps9-{{ .Branch }}-{{ checksum "requirements_test.txt" }}
      # - run:
      #     name: Install system dependencies
      #     command: |
      #       sudo apt install -y libblas-dev liblapack-dev
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements_test.txt
      # - save_cache:
      #     key: deps9-{{ .Branch }}-{{ checksum "requirements_test.txt" }}
      #     paths:
      #       - "/usr/local/bin"
      #       - "/usr/local/lib/python3.10/site-packages"
      - run:
          command: |
            export PYTHONPATH="~/mushroom:$PYTHONPATH"
            export FORCE_COPY=1
            # prepare a test cell database for unit test
            mkdir -p ~/mushroom/db/cell/NaCl
            cp -a ~/mushroom/mushroom/core/test/data/rocksalt.cif ~/mushroom/db/cell/NaCl
            pytest --cov=./
            codecov
