version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4
  python: circleci/python@2.1.1
  #shellcheck: circleci/shellcheck@1.0.0

workflows:
  test:
    jobs:
      - test-py31011
      #- shellcheck/check

jobs:
  test-py31011: &test-template
    working_directory: ~/mushroom
    docker:
      - image: cimg/python:3.10.11 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          PIPENV_VENV_IN_PROJECT: false
          CODECOV_TOKEN: 01359775-2d3e-4223-a0ef-ecc88779e801
          AIMS_SPECIES_DEFAULTS: ~/fake-FHI-aims/species_defaults
    steps:
      - checkout
      # - run: sudo chown -R circleci:circleci /usr/local/bin
      # - run: sudo chown -R circleci:circleci /usr/local/lib/python3.10/site-packages
      # - restore_cache:  # ensure this step occurs *before* installing dependencies
      #     key: deps9-{{ .Branch }}-{{ checksum "requirements_test.txt" }}
      # - run:
      #     name: Install system dependencies
      #     command: |
      #       sudo apt install -y libblas-dev liblapack-dev
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements_test.txt
      # - save_cache:
      #     key: deps9-{{ .Branch }}-{{ checksum "requirements_test.txt" }}
      #     paths:
      #       - "/usr/local/bin"
      #       - "/usr/local/lib/python3.10/site-packages"
      - run:
          name: "Prepare data"
          command: |
            # prepare a test cell database for unit test
            mkdir -p ~/mushroom/db/cell/NaCl
            cp -a ~/mushroom/mushroom/core/test/data/rocksalt.cif ~/mushroom/db/cell/NaCl
            # prepare a fake FHI-aims directory and a H specie for passing the pytest
            mkdir -p $AIMS_SPECIES_DEFAULTS/defaults_2010/tight
            cat "species H" > $AIMS_SPECIES_DEFAULTS/defaults_2010/tight/01_H_default
      - run:
          name: "Linting"
          command: |
            # flake8 commands from https://github.com/logsdail/carmm/blob/master/.github/workflows/linter.yml
            # stop the build if there are Python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - run:
          name: "Testing and coverage"
          command: |
            ls ~/mushroom
            export PYTHONPATH="~/mushroom:$PYTHONPATH"
            export FORCE_COPY=1
            pytest --cov=./
            codecov
