#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""extract the band energies from aims output"""
from argparse import ArgumentParser, RawDescriptionHelpFormatter

from mushroom.aims import read_band_output
from mushroom.core.bs import display_band_analysis

def _parser():
    """the parser"""
    p = ArgumentParser(description=__doc__, formatter_class=RawDescriptionHelpFormatter)
    p.add_argument("out_files", nargs="+", type=str,
                   help="band output files")
    p.add_argument("--unit", default='ev', type=str,
                   help="energy unit")
    return p

def m_aims_gap():
    """the main stream"""
    args = _parser().parse_args()
    bs, kpts = read_band_output(*args.out_files, unit=args.unit)
    display_band_analysis(bs, kpts)


if __name__ == "__main__":
    m_aims_gap()

