#!/usr/bin/env python3
from argparse import ArgumentParser, RawDescriptionHelpFormatter
from mushroom.aims.analyse import StdOut, get_dimensions


def _parser():
    """the parser"""
    p = ArgumentParser(description=__doc__, formatter_class=RawDescriptionHelpFormatter)
    p.add_argument("aimsout")
    return p


if __name__ == '__main__':
    args = _parser().parse_args()
    format_str, dict_str_dim = get_dimensions(args.aimsout)
    for sd in dict_str_dim.items():
        if sd[1] is not None:
            print(format_str % sd)
        else:
            print(format_str % (sd[0], "(NOT FOUND)"))
