#!/usr/bin/env python3
"""Show the symmetry of input structure"""
import argparse
try:
    import spglib
except ImportError:
    spglib = None

from mushroom.core.cell import Cell
from mushroom.core.crystutils import display_symmetry_info, get_density


def _parser():
    """the parse"""
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("input_cell")
    p.add_argument("-i", dest="input_format", default=None,
                   help="Format of input file")
    return p


if __name__ == '__main__':
    args = _parser().parse_args()
    cell = Cell.read(args.input_cell, form=args.input_format)
    density_n, density_m = get_density(cell.latt, cell.atms, latt_unit=cell.unit)
    print("Number density (per ang^3):", density_n)
    print("Mass density (kg per m^3):", density_m)
    if spglib is not None:
        display_symmetry_info(*(cell.get_spglib_input()))
