#!/usr/bin/env python3
"""Show the symmetry of input structure"""
import argparse

from mushroom.core.cell import Cell
from mushroom.core.crystutils import display_symmetry_info

def _parser():
    """the parse"""
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("input_cell")
    p.add_argument("-i", dest="input_format", default=None,
                   help="Format of input file")
    return p


if __name__ == '__main__':
    args = _parser().parse_args()
    cell = Cell.read(args.input_cell, form=args.input_format)
    display_symmetry_info(*(cell.get_spglib_input()))
