#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""analyse VASP CHG/CHGCAR file

The script will do the following:
    - write a cube file for visualization (.cube file in the same path)
"""
from argparse import ArgumentParser, RawDescriptionHelpFormatter
from mushroom.vasp import read_chg

def _parser():
    """the parser"""
    p = ArgumentParser(description=__doc__,
                       formatter_class=RawDescriptionHelpFormatter)
    p.add_argument("-f", dest="pchg", type=str, default="CHGCAR",
                   help="path to the CHGCAR file")
    return p

def m_vasp_chg():
    """main stream"""
    args = _parser().parse_args()
    chg = read_chg(args.pchg)
    with open(args.pchg + ".cube", 'w') as h:
        print(chg.export_cube(), file=h)

if __name__ == "__main__":
    m_vasp_chg()

