#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""draw total density of states from vasp output DOSCAR and export to an XmGrace plot.

TODO: plot spin-up and spin-down
"""
from argparse import ArgumentParser, RawDescriptionHelpFormatter
from mushroom._core.graceplot import Plot
from mushroom.vasp import read_doscar

def _parser():
    """the parser"""
    p = ArgumentParser(description=__doc__, formatter_class=RawDescriptionHelpFormatter)
    p.add_argument("-d", dest="doscar", type=str, default="DOSCAR",
                   help="DOSCAR file to read")
    p.add_argument("-o", dest="output", type=str, default="plotdos.agr",
                   help="path of agr file to export")
    return p.parse_args()

def m_vasp_dos():
    """main stream"""
    args = _parser()
    dos = read_doscar(args.doscar)
    p, ax = Plot.subplots()
    ax.plot(dos.egrid - dos.efermi, dos.get_dos(), color="k", symbol="none", label="Total")
    ax.tight_graph(nyticks=5, yscale=1.2)
    ax.set_xlim(xmin=-6, xmax=6)
    ax.x.set_major(major=3)
    ax.set_ylim(ymin=0.0)
    ax.set_legend(loc="upper left")
    ax.y.set_ticklabel(switch="off")
    ax.x.set_label("Energy ({})".format(dos.unit))
    ax.y.set_label("Density of states [arb. units]")
    ax.axvline(0.0, ls="dashed", lw=3, color="grey")
    p.write(file=args.output)


if __name__ == "__main__":
    m_vasp_dos()
